#!/usr/bin/env python3
"""Extract QuickBASIC graphics statements from a static instruction graph.

The input is emitted by disassemble_qb3.py --instructions-json.  This tool
does not execute or emulate the program.  It groups the Microsoft QB3 runtime
handlers which implement LINE, GET, PUT, VIEW, PAINT, and POINT into the
compound statements generated by the compiler, retaining every setup
instruction so data-dependent coordinates can be translated without guessing.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


GRAPHICS_SYMBOLS = {
    "$LI4": "line_begin",
    "$LI5": "line_end",
    "$LI6": "line_commit",
    "$GE3": "get_begin",
    "$GE4": "get_end",
    "$GE2": "get_commit",
    "$PU2": "put_position",
    "$PU1": "put_commit",
    "$PCO": "graphics_coordinate",
    "$PA1": "paint_commit",
    "$PA2": "paint_commit",
    "$CIR": "circle_commit",
    "$POI": "point_query",
    "$PI1": "point_query",
    "$PI2": "point_query",
}

# These four QB3 VIEW handlers do not have public symbols in the recovered OMF
# map, but their contiguous state transition and every call site are proven in
# BRUN30:3CC3-3DA2.  Keep the runtime addresses in the IR as the authority.
GRAPHICS_TARGETS = {
    "3CC3": "view_begin",
    "3CD9": "view_end",
    "3D11": "view_commit",
    "3DA2": "view_reset_or_statement_end",
}

COMPOUNDS = {
    "line": ["line_begin", "line_end", "line_commit"],
    "line_from_current": ["line_end", "line_commit"],
    "get": ["get_begin", "get_end", "get_commit"],
    "put": ["put_position", "put_commit"],
    "paint": ["graphics_coordinate", "paint_commit"],
    "circle": ["graphics_coordinate", "circle_commit"],
    "view": ["view_begin", "view_end", "view_commit"],
}


def operation_for(instruction: dict[str, object]) -> str | None:
    runtime = instruction.get("runtime")
    if not isinstance(runtime, dict):
        return None
    for symbol in runtime.get("brun30_symbols", []):
        if symbol in GRAPHICS_SYMBOLS:
            return GRAPHICS_SYMBOLS[symbol]
    target = runtime.get("brun30_target")
    return GRAPHICS_TARGETS.get(str(target))


def compact_instruction(item: dict[str, object]) -> dict[str, object]:
    result: dict[str, object] = {
        "address": item["address"],
        "mnemonic": item["mnemonic"],
        "operands": item.get("operands", ""),
    }
    if item.get("comment"):
        result["comment"] = item["comment"]
    return result


def grouped_operations(instructions: list[dict[str, object]]) -> list[dict[str, object]]:
    graphics_indices = [
        index for index, instruction in enumerate(instructions)
        if operation_for(instruction) is not None
    ]
    output: list[dict[str, object]] = []
    cursor = 0
    while cursor < len(graphics_indices):
        first_graphics_index = graphics_indices[cursor]
        first = instructions[first_graphics_index]
        operation = operation_for(first)
        assert operation is not None
        compound_name = next(
            (name for name, sequence in COMPOUNDS.items()
             if sequence[0] == operation),
            None,
        )
        matched_indices = [first_graphics_index]
        if compound_name:
            sequence = COMPOUNDS[compound_name]
            scan = cursor + 1
            for expected in sequence[1:]:
                if scan >= len(graphics_indices):
                    matched_indices = []
                    break
                candidate_index = graphics_indices[scan]
                candidate = instructions[candidate_index]
                if (candidate.get("function_start") != first.get("function_start") or
                        operation_for(candidate) != expected):
                    matched_indices = []
                    break
                matched_indices.append(candidate_index)
                scan += 1
        if compound_name and matched_indices:
            start = max(
                0,
                (graphics_indices[cursor - 1] + 1) if cursor else
                first_graphics_index - 12,
            )
            end = matched_indices[-1] + 1
            output.append({
                "kind": compound_name,
                "address": first["address"],
                "end_address": instructions[matched_indices[-1]]["address"],
                "function_start": first.get("function_start"),
                "function_name": first.get("function_name"),
                "handlers": [
                    {
                        "address": instructions[index]["address"],
                        "operation": operation_for(instructions[index]),
                        "runtime": instructions[index]["runtime"],
                    }
                    for index in matched_indices
                ],
                "static_setup": [
                    compact_instruction(item) for item in instructions[start:end]
                ],
            })
            cursor += len(matched_indices)
            continue

        # A standalone handler is retained rather than silently discarded.
        start = max(0, first_graphics_index - 12)
        output.append({
            "kind": operation,
            "address": first["address"],
            "end_address": first["address"],
            "function_start": first.get("function_start"),
            "function_name": first.get("function_name"),
            "handlers": [{
                "address": first["address"],
                "operation": operation,
                "runtime": first["runtime"],
            }],
            "static_setup": [
                compact_instruction(item)
                for item in instructions[start:first_graphics_index + 1]
            ],
        })
        cursor += 1
    return output


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("instructions", type=Path)
    parser.add_argument("--json", required=True, type=Path, dest="output")
    args = parser.parse_args()

    source = json.loads(args.instructions.read_text(encoding="utf-8"))
    instructions = source.get("instructions")
    if not isinstance(instructions, list):
        parser.error("input has no static instruction graph")
    operations = grouped_operations(instructions)
    counts = Counter(str(item["kind"]) for item in operations)
    report = {
        "format": "QuickBASIC 3 static graphics statement IR v1",
        "method": "static runtime-handler grouping; no DOS execution or emulation",
        "source": str(args.instructions.resolve()),
        "module": source.get("module"),
        "operation_count": len(operations),
        "operation_counts": dict(sorted(counts.items())),
        "operations": operations,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(args.output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
