#ifndef MW_GAME_H
#define MW_GAME_H

#include "mw_types.h"
#include "mw_video.h"
#include "mw_input.h"

/* Dungeon map constants */
#define MAP_W       80
#define MAP_H       110
#define MONSTER_MAP_LAYERS 3
#define MONSTERS_PER_FLOOR 145
#define PIT_GROUP_FLOORS   32
#define PIT_ROW_BYTES      10

/* The DOS MON.MAP record is deliberately kept byte-for-byte compatible. */
typedef struct MonsterRecord {
    u8 x, y;
    u8 hp_lo, hp_hi;
    u8 type;
    u8 level;
} MonsterRecord;

/* Packed convenience encoding returned by map_get_cell().  DUNG.BIN itself
 * is not a cell array; the four values are generated by map_get_edge(). */
#define WALL_N_MASK  0x03
#define WALL_E_MASK  0x0C
#define WALL_S_MASK  0x30
#define WALL_W_MASK  0xC0

/* Global game state — replaces the DS-relative globals from the original */
typedef struct Game {
    /* Video */
    Video video;
    int   video_mode;           /* original chipset mode (8 = 1024x768 here) */
    int   screen_w;
    int   screen_h;

    /* Input */
    Input input;

    /* Players */
    int        num_players;     /* 1 or 2 */
    int        cur_player;      /* 0 or 1 */
    int        player_slot[2];  /* save slot index for each player */
    Character  chars[MAX_PLAYERS];
    int        char_exists[MAX_PLAYERS];

    /* Dungeon state */
    int   cur_floor;
    int   cur_x, cur_y;
    int   last_move_dir;        /* 0=N, 1=S, 2=W, 3=E (matches original g_C89C) */
    int   view_mode;            /* 0-2, cycled by Z key (matches original g_45C9) */
    u8   *dungeon_data;         /* loaded from dung.bin */
    int   dungeon_data_size;
    u8   *worldmap_data;        /* loaded from worldmap.bin */
    u8    visited[MAP_H][MAP_W]; /* fog of war: 1 = player has seen this cell */
    int   monster_adjacent;      /* set when calc_damage finds monster nearby */

    /* Persistent dungeon actors.  The original save keeps three 145-record
     * floor layers in <slot>MON.MAP and rotates a layer in when needed. */
    int   active_save_slot;
    u8    monster_floor[MONSTER_MAP_LAYERS];
    MonsterRecord monster_map[MONSTER_MAP_LAYERS][MONSTERS_PER_FLOOR];
    int   monster_layer;
    int   monster_map_loaded;
    int   monster_map_dirty;

    /* Exact sparse <slot><floor/32>.DUN bit grid.  The game uses these bits
     * to remember squares whose one-shot pitfall has already fired. */
    u8    pit_used[PIT_GROUP_FLOORS][MAP_H][PIT_ROW_BYTES];
    u8    pit_row_mask[PIT_GROUP_FLOORS][16];
    u32   pit_floor_mask;
    int   pit_group;
    int   pit_state_loaded;
    int   pit_state_dirty;

    /* Graphics assets */
    u8   *world_pic_data[256];  /* image table from world.pic */
    int   world_pic_sizes[256];
    int   world_pic_count;
    u8   *wall_pic_data[64];    /* wall tile images from wall.pic */
    int   wall_pic_sizes[64];
    int   wall_pic_count;
    u8   *wall_texture[2];      /* decoded 256x200 WALL.PIC surfaces */

    /* Monster data */
    u8   *monster_data;         /* from h.bin */

    /* File paths */
    char  game_dir[260];        /* directory containing game data files */

    /* RNG */
    u32   rand_state;
} Game;

/* Core lifecycle */
int  game_init(Game *g, const char *data_dir);
void game_shutdown(Game *g);
void game_run(Game *g);
void game_draw_exploration(Game *g, Character *player);
void game_draw_combat_overlay(Game *g, Character *player,
                              int entity_index, int monster_type,
                              int monster_level, int monster_hp,
                              const char *msg1, const char *msg2,
                              const char *msg3);
void game_update_visibility(Game *g);

/* Character I/O */
int  game_load_character(Game *g, int slot);
int  game_save_character(Game *g, int slot);
int  game_load_world_state(Game *g, int slot);
int  game_save_world_state(Game *g);

/* Asset loading */
int  game_load_pics(Game *g);
int  game_load_dungeon(Game *g);
int  game_load_monsters(Game *g);

/* Dungeon map access */
u8   map_get_cell(Game *g, int x, int y);
int  map_get_edge(Game *g, int x, int y, int axis);
int  game_can_move(Game *g, int ox, int oy, int nx, int ny);
int  map_is_wall(Game *g, int x, int y);
int  map_has_wall_n(u8 cell);
int  map_has_wall_e(u8 cell);
int  map_has_wall_s(u8 cell);
int  map_has_wall_w(u8 cell);

/* Persistent monsters and floor features. */
int  game_find_monster(Game *g, int x, int y);
int  game_find_adjacent_monster(Game *g);
int  game_monster_hp(Game *g, int index);
void game_set_monster_hp(Game *g, int index, int hp);
void game_kill_monster(Game *g, int index);
void game_advance_monsters(Game *g, Character *player);
int  game_change_floor(Game *g, Character *player, int new_floor);
int  game_relocate(Game *g, Character *player);
int  game_pass_wall(Game *g, Character *player);
int  game_ladder_delta(Game *g, int x, int y);
int  game_trapdoor_floor(Game *g, int x, int y);
int  game_shop_type(Game *g, int x, int y);
int  game_apply_pitfall(Game *g, Character *player);

/* RNG — matches original LCG */
int  game_rand(Game *g);
void game_srand(Game *g, u32 seed);

/* File path helper */
void game_make_path(Game *g, char *out, int out_sz, const char *filename);

/* Drawing helpers (internal to mw_game.c) */
void draw_minimap(Game *g, int mx, int my, int mw, int mh);

#endif /* MW_GAME_H */
