#ifndef MW_GAME_H
#define MW_GAME_H

#include "mw_types.h"
#include "mw_video.h"
#include "mw_input.h"
#include "mw_audio.h"

/* Dungeon map constants */
#define MAP_W       80
#define MAP_H       110
#define MONSTER_MAP_LAYERS 3
#define MONSTERS_PER_FLOOR 145
#define PIT_GROUP_FLOORS   32
#define PIT_ROW_BYTES      10
#define BESTIARY_MONSTER_COUNT 178
#define BESTIARY_CATALOG_COUNT 161

/* Native MON.MAP v3 record.  Legacy DOS and native-v2 records are imported
 * on load.  Floors/levels are 16-bit and HP is 32-bit so the 1,000-floor
 * endgame does not flatten every late monster at 65,535 health. */
#pragma pack(push, 1)
typedef struct MonsterRecord {
    u8 x, y;
    u32 hp;
    u8 type;
    u16 level;
} MonsterRecord;
#pragma pack(pop)

_Static_assert(sizeof(MonsterRecord) == 9, "native monster record layout");

/* Packed convenience encoding returned by map_get_cell().  DUNG.BIN itself
 * is not a cell array; the four values are generated by map_get_edge(). */
#define WALL_N_MASK  0x03
#define WALL_E_MASK  0x0C
#define WALL_S_MASK  0x30
#define WALL_W_MASK  0xC0

/* Global game state — replaces the DS-relative globals from the original */
typedef struct Game {
    /* Video */
    Video video;
    int   video_mode;           /* original chipset mode (8 = 1024x768 here) */
    int   screen_w;
    int   screen_h;

    /* Input */
    Input input;
    MwAudio audio;

    /* Players */
    int        num_players;     /* native session count; original is one character */
    int        cur_player;      /* 0 or 1 */
    int        player_slot[2];  /* save slot index for each player */
    Character  chars[MAX_PLAYERS];
    int        char_exists[MAX_PLAYERS];

    /* Dungeon state */
    int   cur_floor;
    int   cur_x, cur_y;
    int   dungeon_max_floor;    /* 250 Classic, 1000 Enhanced */
    int   dungeon_number;       /* original character field +0x7B2 / g_C8A4 */
    int   last_move_dir;        /* 0=N, 1=S, 2=W, 3=E (matches original g_C89C) */
    int   view_mode;            /* 0-2, cycled by Z key (matches original g_45C9) */
    int   brick_speed;          /* 0-3, compatibility setting cycled by B */
    int   sound_enabled;        /* original O-key on/off state */
    int   map_player_visible;   /* timed blink phase for the map cursor */
    /* Native runtime testing controls.  They are intentionally not serialized
       into the original 0x928-byte character or WORLD sidecar formats. */
    int   cheat_noclip;
    int   cheat_god_mode;
    int   cheat_open_floor;
    int   bestiary_unlock_all;
    u32   advice_counter;       /* WORLD func_1D5A7 contextual hint cycle */
    u8    wall_color_r;         /* hidden '*': palette background red */
    u8    wall_color_g;         /* hidden '(': palette background green */
    u8    wall_color_b;         /* hidden ')': palette background blue */
    u8   *dungeon_data;         /* loaded from dung.bin */
    int   dungeon_data_size;
    u8   *worldmap_data;        /* loaded from worldmap.bin */
    int   worldmap_data_size;
    int   wilderness_x;         /* WORLD g_C8EA: wrapped 0x40..0x3F80 */
    int   wilderness_y;         /* WORLD g_C8EC: wrapped 0x40..0x1F80 */
    int   wilderness_boat;      /* WORLD g_C8F2 */
    int   wilderness_initialized;
    u8    visited[MAP_H][MAP_W]; /* fog of war: 1 = player has seen this cell */
    int   monster_adjacent;      /* set when calc_damage finds monster nearby */

    /* Persistent dungeon actors.  The original save keeps three 145-record
     * floor layers in <slot>MON.MAP and rotates a layer in when needed. */
    int   active_save_slot;
    u16   monster_floor[MONSTER_MAP_LAYERS];
    MonsterRecord monster_map[MONSTER_MAP_LAYERS][MONSTERS_PER_FLOOR];
    int   monster_layer;
    int   monster_map_loaded;
    int   monster_map_dirty;

    /* Exact sparse <slot><floor/32>.DUN bit grid.  The game uses these bits
     * to remember explored squares so discovered chutes/shafts can be marked
     * when their floor is visited again.  A known chute still triggers. */
    u8    pit_used[PIT_GROUP_FLOORS][MAP_H][PIT_ROW_BYTES];
    u8    pit_row_mask[PIT_GROUP_FLOORS][16];
    u32   pit_floor_mask;
    int   pit_group;
    int   pit_state_loaded;
    int   pit_state_dirty;

    /* Per-character monster record, indexed by the original raw monster
     * type.  Only the 95 graphics-eligible types are serialized/cataloged. */
    u32   bestiary_kills[BESTIARY_MONSTER_COUNT];
    int   bestiary_loaded;
    int   bestiary_dirty;

    /* Graphics assets */
    u8   *world_pic_data[256];  /* image table from world.pic */
    int   world_pic_sizes[256];
    int   world_pic_count;
    u8   *wall_pic_data[64];    /* wall tile images from wall.pic */
    int   wall_pic_sizes[64];
    int   wall_pic_count;
    u8   *wall_texture[2];      /* decoded 256x200 WALL.PIC surfaces */

    /* Monster data */
    u8   *monster_data;         /* from h.bin */

    /* File paths */
    char  game_dir[260];        /* directory containing game data files */

    /* RNG */
    u32   rand_state;
} Game;

/* Every mechanic capable of changing dungeon depth must take its limits from
 * this table.  Keeping the original Classic constants explicit prevents an
 * Enhanced traversal change from leaking into a 251-floor character. */
typedef struct GameTraversalRules {
    int max_floor;
    int prep_ascend_max_floor;
    int prep_descend_max_floor;
    int prep_major_descend_cap;
    int dig_max_floor;
    int dig_reverse_floor;
    int dig_direction_floor;
    int dig_slow_floor;
    int dig_search_attempts;
} GameTraversalRules;

/* Core lifecycle */
int  game_init(Game *g, const char *data_dir);
void game_shutdown(Game *g);
void game_run(Game *g);
void game_draw_exploration(Game *g, Character *player);
void game_draw_combat_overlay(Game *g, Character *player,
                              int entity_index, int monster_type,
                              int monster_level, int monster_hp,
                              const char *msg1, const char *msg2,
                              const char *msg3);
void game_draw_bestiary_test(Game *g, int selected);
void game_draw_game_stats_test(Game *g, Character *player);
int  game_ui_self_test(Game *g);
void game_update_visibility(Game *g);
const GameTraversalRules *game_traversal_rules(const Game *g);
int  game_dungeon_max_floor(const Game *g);
int  game_clamp_dungeon_floor(const Game *g, int floor);
/* Shared modal-menu mouse helpers.  SDL events carry window coordinates;
 * these reproduce DOS mouse hit maps in the port's 1024x768 logical space. */
int  game_mouse_click_logical(Game *g, int *x, int *y);
int  game_mouse_row(Game *g, int x0, int x1, int y0, int row_height,
                    int row_count);
int  game_mouse_command_key(Game *g);
int  game_mouse_view_direction(Game *g);

/* Character I/O */
int  game_load_character(Game *g, int slot);
int  game_save_character(Game *g, int slot);
int  game_load_world_state(Game *g, int slot);
int  game_save_world_state(Game *g);
int  game_load_bestiary(Game *g, int slot);
int  game_save_bestiary(Game *g);

/* Asset loading */
int  game_load_pics(Game *g);
int  game_load_dungeon(Game *g);
int  game_load_monsters(Game *g);

/* Dungeon map access */
u8   map_get_cell(Game *g, int x, int y);
int  map_get_edge(Game *g, int x, int y, int axis);
int  game_can_move(Game *g, int ox, int oy, int nx, int ny);
int  map_is_wall(Game *g, int x, int y);
int  map_has_wall_n(u8 cell);
int  map_has_wall_e(u8 cell);
int  map_has_wall_s(u8 cell);
int  map_has_wall_w(u8 cell);

/* Persistent monsters and floor features. */
int  game_find_monster(Game *g, int x, int y);
int  game_find_adjacent_monster(Game *g);
int  game_monster_hp(Game *g, int index);
void game_set_monster_hp(Game *g, int index, int hp);
void game_kill_monster(Game *g, int index);
void game_advance_monsters(Game *g, Character *player);
unsigned long long game_loaded_weight(const Character *player);
int  game_weight_monster_turns(const Character *player);
int  game_change_floor(Game *g, Character *player, int new_floor);
int  game_relocate(Game *g, Character *player);
int  game_pass_wall(Game *g, Character *player);
void game_begin_new_dungeon(Game *g, Character *player, int dungeon_number);
int  game_ladder_delta(Game *g, int x, int y);
int  game_trapdoor_floor(Game *g, int x, int y);
int  game_shop_type(Game *g, int x, int y);
int  game_apply_pitfall(Game *g, Character *player);
int  game_is_known_pitfall(Game *g, int x, int y);
void game_refresh_world_palette(Game *g);

/* RNG — matches original LCG */
int  game_rand(Game *g);
void game_srand(Game *g, u32 seed);

/* File path helper */
void game_make_path(Game *g, char *out, int out_sz, const char *filename);

/* Drawing helpers (internal to mw_game.c) */
void draw_minimap(Game *g, int mx, int my, int mw, int mh);

/* Read-only deterministic regression checks for town economy and drops. */
int game_economy_self_test(void);
int game_weight_self_test(void);

#endif /* MW_GAME_H */
